sudo: required
language: node_js
node_js:
  - "0.10.25"

addons:
  postgresql: "9.4"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgif-dev

  - cd $TRAVIS_BUILD_DIR

  # Configure postgres
  - psql -c 'create database collabospheretravis;' -U postgres
  - psql collabospheretravis -c 'create extension pg_trgm;' -U postgres

script:
  - node_modules/.bin/gulp test-travis
